### ISSUE TITLE
Heap randomness on plotting

### ISSUE THREAD

**Issue by simozhou** [simozhou/homework3#2]
We need to figure out what the professor wants: as long as he's fine with it, we'll have no problem. If he's not into this, we need to fix this bug by setting insertion and deletion to be **ORDERED**, so that we can have a measure of the worst case scenario in every testing loop.

**Comment by simozhou** [comment]
related to #3

**Comment by jaydee220** [comment]
As discussed with Ioannis, random values are to be used --> With the help of statistics we need to remove outlayers and get a plot

**Comment by simozhou** [comment]
agreed, closing this issue.
