### ISSUE TITLE
Statistics on values

### ISSUE THREAD

**Issue by simozhou** [simozhou/homework3#3]
We need to add statistics to our testing procedure. the idea is to collect for each array size of each test an array of values (~10 roughly). From this we need to calculate the standard deviation of the sample, and spot the outliers (MAD/percentile method to be decided).

**Comment by jaydee220** [comment]
the question here is how many times to repeat the function/test. Proposition of prof to take sd of n times and compare it to the sd of n+1 until the sd doesn't change anymore significantly.

**Comment by simozhou** [comment]
the point is that the standard deviation is not something to be minimized, but something to be aware of when computing our statistics. For each point in each plot we will have a sample of measurements which will be de-outlierized, and will have a specific mean and standard **error**. We have to transform each point into an interval which looks like:

![confint](https://user-images.githubusercontent.com/32101556/33742172-67e83888-dba7-11e7-929a-9c45ad58bf04.gif)


I believe the best is to start with `array_size = 10` and check if there is any significant difference in performance 🌟 . if not, let this value grow. We also need to figure out how to embed this confidence interval into out test_results, and successively into our dataframe. 

the best would be to have a plot which has points which are the means, and for each point a vertical line which would represent the standard **error** of the sample. 

so, our main jobs are:

1. implement an outliers-spotting function
2. find a way to get our point value well put into our dataframe
3. plot nicely our results

we don't have time for this, but would be interesting to implement also some fitting over those values, because that is our **#projectgoal**.

**Comment by simozhou** [comment]
I have found my ideal plot [here](https://stackoverflow.com/questions/22481854/plot-mean-and-standard-deviation). It is the way i would like to represent the data; it also gives clues on how to store the standard error into the dataframe... by simply adding it as a new key in the `self.test_result` dict! each function will have a `function_name_se` which will be a value too.

**Comment by simozhou** [comment]
closing issue with _statistify implementation
